modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory
issueTrackerURL="https://github.com/caltinor" #optional
displayURL="https://github.com/caltinor" #optional
#logoFile="" #optional
credits="Thanks to the MMD community." #optional
authors="Caltinor" #optional
license="ARR License"

[[mods]] #mandatory
modId="dicemcta" #mandatory
version="${file.jarVersion}" #mandatory
displayName="DiceMC Tiered Armor" #mandatory
#updateJSONURL=""
description='''
Logical and progressive armor.
'''

[[dependencies.enderthing]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37.0.1,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.enderthing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"