modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
issueTrackerURL="https://github.com/caltinor" #optional
displayURL="https://github.com/caltinor" #optional
#logoFile="" #optional
credits="Thanks to the MMD community." #optional
authors="Caltinor" #optional
license="ARR License"

[[mods]] #mandatory
modId="dicemcta" #mandatory
version="${file.jarVersion}" #mandatory
displayName="DiceMC Tiered Armor" #mandatory
#updateJSONURL=""
description='''
Logical and progressive armor.
'''

[[dependencies.dicemcta]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40.0.18,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.dicemcta]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"